/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: qdupless <marvin@42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2016/08/02 17:47:00 by qdupless          #+#    #+#             */
/*   Updated: 2016/11/19 15:36:56 by qdupless         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "ft_printf.h"
#include <stdio.h>

int		main(void)
{
	int		i;
	int		j;
	short int k = 4;

	j = ft_printf("%-25s\n", NULL);
	i = printf("%-25s\n", NULL);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	j = ft_printf("%25s\n", NULL);
	i = printf("%25s\n", NULL);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	j = ft_printf("%2.567d\n", 54);
	i = printf("%2.567d\n", 54);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	j = ft_printf("%5o\n", 90);
	i = printf("%5o\n", 90);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	j = ft_printf("%6x\n", 50);
	i = printf("%6x\n", 50);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	j = ft_printf("%24u\n", 44);
	i = printf("%24u\n", 44);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	j = ft_printf("%10s is a string\n", "this");
	i = printf("%10s is a string\n", "this");
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	j = ft_printf("%-10s is a string\n", "");
	i = printf("%-10s is a string\n", "");
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	j = ft_printf("%d\n", -1);
	i = printf("%d\n", -1);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	j = ft_printf("%05d\n", -42);
	i = printf("%05d\n", -42);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%05%\n");
	j = ft_printf("%05%\n");
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%X\n", -42);
	j = ft_printf("%X\n", -42);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%.2s\n", "salut");
	j = ft_printf("%.2s\n", "salut");
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf(" %20.45% \n");
	j = ft_printf(" %20.45% \n");
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%-15x\n", 542);
	j = ft_printf("%-15x\n", 542);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%-10x\n", 42);
	j = ft_printf("%-10x\n", 42);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%-5%\n");
	j = ft_printf("%-5%\n");
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%X\n", 0);
	j = ft_printf("%X\n", 0);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%x\n", 0);
	j = ft_printf("%x\n", 0);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%05x\n", 0);
	j = ft_printf("%05x\n", 0);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%-6X\n", 0);
	j = ft_printf("%-6X\n", 0);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%04X\n", 0);
	j = ft_printf("%04X\n", 0);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%-10x\n", 0);
	j = ft_printf("%-10x\n", 0);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%+5d\n", 0);
	j = ft_printf("%+5d\n", 0);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%+06d\n", 54);
	j = ft_printf("%+06d\n", 54);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%+d\n", 42);
	j = ft_printf("%+d\n", 42);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%-12o\n", 0);
	j = ft_printf("%-12o\n", 0);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%x\n", -42);
	j = ft_printf("%x\n", -42);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%-10O\n", 0);
	j = ft_printf("%-10O\n", 0);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%06u\n", 0);
	j = ft_printf("%06u\n", 0);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%-10U\n", 0);
	j = ft_printf("%-10U\n", 0);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%.4d\n", 2);
	j = ft_printf("%.4d\n", 2);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%05.10o\n", 42);
	j = ft_printf("%05.10o\n", 42);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%-10.5x\n", 55);
	j = ft_printf("%-10.5x\n", 55);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%+15.4d\n", 32);
	j = ft_printf("%+15.4d\n", 32);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%-5d\n", -42);
	j = ft_printf("%-5d\n", -42);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%5.2x\n", 5427);
	j = ft_printf("%5.2x\n", 5427);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%#8x\n", 42);
	j = ft_printf("%#8x\n", 42);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%#08x\n", 42);
	j = ft_printf("%#08x\n", 42);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%-10.2s is a string\n", "this");
	j = ft_printf("%-10.2s is a string\n", "this");
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%5.2s is a string\n", "this");
	j = ft_printf("%5.2s is a string\n", "this");
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%5.2s is a string\n", "");
	j = ft_printf("%5.2s is a string\n", "");
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%-5.2s is a string\n", "");
	j = ft_printf("%-5.2s is a string\n", "");
	ft_putnbr(i);  
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%2c\n", 0);
	j = ft_printf("%2c\n", 0);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%-5.10o\n", 2500);
	j = ft_printf("%-5.10o\n", 2500);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%-10.5o\n", 2500);
	j = ft_printf("%-10.5o\n", 2500);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%5d\n", -42);
	j = ft_printf("%5d\n", -42);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("% d\n", 42);
	j = ft_printf("% d\n", 42);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%4.15d\n", 42);
	j = ft_printf("%4.15d\n", 42);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%+10.5d\n", 4242);
	j = ft_printf("%+10.5d\n", 4242);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("% 10.5d\n", 4242);
	j = ft_printf("% 10.5d\n", 4242);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%+10.5d\n", 4242);
	j = ft_printf("%+10.5d\n", 4242);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%03.2d\n", 1);
	j = ft_printf("%03.2d\n", 1);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%03.2d\n", 0);
	j = ft_printf("%03.2d\n", 0);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%2hd\n", k);
	j = ft_printf("%2hd\n", k);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%+5hd\n", k);
	j = ft_printf("%+5hd\n", k);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%-10.2hd\n", k);
	j = ft_printf("%-10.2hd\n", k);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%lx\n", 4294967296);
	j = ft_printf("%lx\n", 4294967296);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%jx\n", 4294967295);
	j = ft_printf("%jx\n", 4294967295);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%ju\n", 4294967296);
	j = ft_printf("%ju\n", 4294967296);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%zd\n", 4294967296);
	j = ft_printf("%zd\n", 4294967296);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%zd\n", 4294967295);
	j = ft_printf("%zd\n", 4294967295);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%jd\n", 9223372036854775807);
	j = ft_printf("%jd\n", 9223372036854775807);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%ld\n", 2147483648);
	j = ft_printf("%ld\n", 2147483648);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%jx\n", -4294967297);
	j = ft_printf("%jx\n", -4294967297);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%jx\n", -4294967297);
	j = ft_printf("%jx\n", -4294967297);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%C\n", L'α');
	j = ft_printf("%C\n", L'α');
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%S\n", L"我是一只猫");
	j = ft_printf("%S\n", L"我是一只猫。");
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%.3S\n", L"我是一只猫");
	j = ft_printf("%.3S\n", L"我是一只猫");
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i = printf("%.3o\n", 4242);
	j = ft_printf("%.3o\n", 4242);
	ft_putnbr(i);
	ft_putnbr(j);
	ft_putendl("");
	i  = printf("%d %s %o", 42, "salut");
}
